### ISSUE TITLE
Check trace and span ID lengths. Warning if incorrect

### ISSUE THREAD

**Issue by agardnerIT** [agardnerIT/logpusher#2]
We know from the opentelemetry specification that:
- A trace ID must be 16bytes (32 characters) long
- A span ID must be 8bytes (16 characters) long

If trace and / or span ID are provided, logpusher should warn when the user provides input that does not equal those lengths.

In other words, if a user tries to send a trace ID that is anything other than 32 characters long, logpusher should warn them because we know an error will occur during the push to the collector.

Similarly, if a user tries to send a span ID that is anything other than 16 characters long, logpusher should warn.

### Examples

```
# Trace ID is too short (31 characters). Collector will fail to accept it.
% docker run gardnera/logpusher:v0.1.0 -ep http://1.2.3.4:4318 -c "This is my log line" --trace-id "1234567890123456789012345678901"
<Response [400]>

# This trace is 32 characters long. Collector will accept it.
% docker run gardnera/logpusher:v0.1.0 -ep http://1.2.3.4:4318 -c "This is my log line" --trace-id "12345678901234567890123456789012"
<Response [200]>

# This span ID is the correct length (16 characters). Collector will accept it.
% docker run gardnera/logpusher:v0.1.0 -ep http://1.2.3.4:4318 -c "This is my log line" --span-id "1234567890123456"      
<Response [200]>

# This span ID is only 15 chars long. Collector will fail to accept it.
% docker run gardnera/logpusher:v0.1.0 -ep http://1.2.3.4:4318 -c "This is my log line" --span-id "123456789012345" 
<Response [400]>
```

Documentation pages should also be included to leave a hint as to this "rule".

**Comment by agardnerIT** [comment]
@MilijanBogdanovic this is basically the same fix as you did for tracepusher. Fancy taking it on?

**Comment by bogdanovicdev** [comment]
Hey Adam, 
Yes of course sorry for the late reply I was on vacation.
Will get it done in a day or two, if thats ok 
@agardnerIT

**Comment by bogdanovicdev** [comment]
Hey @agardnerIT 
Just a follow up for this, sorry for the late reply, I was/ am unable to patch this in the next 7,8 days, as my laptop 
 is away from me. However, I will try with another PC, and will probably just patch this in 3,4 days, if that is not too late for you to wait.
Once again sorry for the delayed message and update

**Comment by agardnerIT** [comment]
No worries at all. Take your time. No rush :)

**Comment by bogdanovicdev** [comment]
Hey @agardnerIT,
Sorry for being late on this!
Please find the my PR attached on this repo, with the simple change and doc update.
LMK if you envisioned this a bit differently or wanted smth else, more than happy to change.
Thanks!

**Comment by agardnerIT** [comment]
Thanks! All good! Merged.
